listenAddress: :8050

authorizationServiceUrl: http://localhost:8000/atlas/api/v1/authorize/

cors:
  allowedOrigins:
    - http://localhost:8000
  allowedHeaders:
    - Accept
    - Authorization
    - Content-Type
    - X-Requested-With
  allowCredentials: true
  allowPrivateNetwork: true
  debugLogging: true

paths:
  - path: /api/ows
    backend:
      slug: geoserver
      path: /ows
    allowedMethods:
      - GET
      - POST
  - path: /api/kvk/zoeken
    backend:
      slug: kvk
      path: /zoeken

backends:
  geoserver:
    type: OWS
    baseUrl: http://localhost:8080/geoserver
  kvk:
    type: REST
    baseUrl: https://api.kvk.nl/test/api/v2
    auth:
      header:
        apikey: l7xx1f2691f2520d487b902f4e0b57a0b197