version: "3.7"

services:
  loki:
    image: grafana/loki:2.9.1
    ports:
      - 3100:3100
    volumes:
      - loki-data:/loki
  grafana:
    image: grafana/grafana:10.1.1
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
  loki-data:
