version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    command: "start-dev"
    ports:
      - 8081:8080
