name: Create GitHub release and attach binaries

permissions:
  contents: read
  pull-requests: write

on:
  push:
    tags: [ '*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # pin@4.1.0
        with:
          go-version: '1.21'
      - name: Build Filter-proxy Binaries
        run: |
          make build-cross
          make dist checksum VERSION="${{ github.ref_name }}"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            _dist/filter-proxy-${{ github.ref_name }}-darwin-amd64.tar.gz
            _dist/filter-proxy-${{ github.ref_name }}-darwin-amd64.tar.gz.sha256
            _dist/filter-proxy-${{ github.ref_name }}-darwin-arm64.tar.gz
            _dist/filter-proxy-${{ github.ref_name }}-darwin-arm64.tar.gz.sha256
            _dist/filter-proxy-${{ github.ref_name }}-linux-amd64.tar.gz
            _dist/filter-proxy-${{ github.ref_name }}-linux-amd64.tar.gz.sha256
            _dist/filter-proxy-${{ github.ref_name }}-linux-arm64.tar.gz
            _dist/filter-proxy-${{ github.ref_name }}-linux-arm64.tar.gz.sha256
            _dist/filter-proxy-${{ github.ref_name }}-windows-amd64.zip
            _dist/filter-proxy-${{ github.ref_name }}-windows-amd64.zip.sha256
